name: Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to merge'
        required: true
        type: string

permissions:
  pull-requests: write
  checks: read

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.pull_request.number || github.event.inputs.pr_number }};
            
            // Get PR status
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            // Check if all checks have passed
            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.data.head.sha
            });

            const allChecksPassed = checks.data.check_runs.every(check => check.conclusion === 'success');
            
            if (!allChecksPassed) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: 'Cannot merge PR: Not all checks have passed.'
              });
              return;
            }

            // Merge the PR
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            }); 