name: Validate and Merge

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to validate and merge'
        required: true
        type: string
      pr_number:
        description: 'PR number to merge'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Validate files
        run: uv run --script src/processors/frontmatter_validator.py archive

  merge:
    needs: validate
    if: needs.validate.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            
            // Merge the PR
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            });

  close-pr:
    needs: validate
    if: needs.validate.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.inputs.pr_number }};
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'Cannot merge PR: Validation failed. Closing PR.'
            });
            
            // Close the PR
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              state: 'closed'
            }); 